queue_rules:
  - name: default
defaults:
  actions:
  queue_rule:
    merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|auto-merge|dependencies
    actions:
      queue:
